package client;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
/*import javax.swing.*;
import java.io.*;
import javax.swing.event.*;
import javax.swing.text.html.*;
import java.awt.event.*;
import java.awt.*;
import java.util.*;
import java.rmi.*;*/


public class MlbStatsGuiClient extends MlbStatsGui implements ActionListener, ItemListener {
	

	private static final long serialVersionUID = 1L;
	
	private static final boolean debugOn = true;
	//private gui.MlbStatsGui stats;

	public MlbStatsGuiClient(String fName, String lName, String team) {
		btnCompareToPlayer.addActionListener(this);
		btnSeePlayerStats.addActionListener(this);
		SubmitPlayerSearchButton.addActionListener(this);
	}
	
	private void debug(String message) {
		if (debugOn)
			System.out.println("debug: " + message);
	}
	
	@Override
	public void itemStateChanged(ItemEvent e) {
		try {			
			/*if (event.getStateChange() == ItemEvent.SELECTED) {
				Object comp = event.getSource();
				debug("Selection event generated by "
						+ ((comp == frWps) ? "from " : "to ") + "combobox. "
						+ "Selected waypoint is: " + (String) event.getItem());

				String frmWp = (String) event.getItem();
				Waypoint tempWp = server.get(frmWp);
				latIn.setText(String.valueOf(tempWp.getLat()));
				lonIn.setText(String.valueOf(tempWp.getLon()));
				eleIn.setText(String.valueOf(tempWp.getEle()));
				nameIn.setText(tempWp.getName());
				addrIn.setText(tempWp.getName());
				}*/
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getActionCommand().equals("SubmitPlayerSearchButton")) {
			try {
				debug("you clicked Submit Search");
				String fName = txtFirstName.getText().toString();
				String lName = txtLastName.getText().toString();
				String team = txtTeam.getText().toString();
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		} else if (e.getActionCommand().equals("SeePlayerStats")) {
			try {
                // when user highlighted in the table
                // access Player stats
                //make new Jpanel pop up (MLBPlayerProfile.java)
				debug("you clicked See Player Stats");
				String fName = txtFirstName.getText().toString();
				String lName = txtLastName.getText().toString();
				String team = txtTeam.getText().toString();
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		} else if (e.getActionCommand().equals("CompareToPlayer")) {
			try {
				debug("you clicked Compare to Player");
				String fName = txtFirstName.getText().toString();
				String lName = txtLastName.getText().toString();
				String team = txtTeam.getText().toString();
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		}		
	}
}
